package polyflow;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Stage 3: DSL Rule Parser and Rule Evaluation Engine.
 *
 * <p>Reads the metrics generated by Fortran, parses the external DSL rules,
 * evaluates the rules and generates the alert, MIPS sequence and HTML
 * report files.</p>
 *
 * @author Randall AC
 * @author Keilor MC
 */
public final class RuleEvaluator {

    private RuleEvaluator() {
    }

    /**
     * Base class for all DSL rules.
     *
     * <p>Every concrete rule is bound to exactly one Fortran metric and
     * knows how to compare its current value against a threshold using
     * the operator declared in the rules file. Subclasses only need to
     * supply the metric name, unit and the numeric code expected by the
     * MIPS stage — the comparison logic itself is shared here.</p>
     */
    public static abstract class Regla {

        private final String nombreRegla;
        private final String operador;
        private final double valorUmbral;
        private final String metrica;
        private final String unidad;

        /**
         * Creates a new rule bound to a specific metric.
         *
         * @param nombreRegla rule identifier as declared in the DSL file
         * @param operador comparison operator ({@code >}, {@code <},
         *         {@code >=} or {@code <=})
         * @param valorUmbral threshold value the metric is compared against
         * @param metrica name of the Fortran metric this rule reads
         * @param unidad display unit for the metric (e.g. {@code "C"},
         *         {@code "mm"})
         */
        protected Regla(
                String nombreRegla,
                String operador,
                double valorUmbral,
                String metrica,
                String unidad) {

            this.nombreRegla = nombreRegla;
            this.operador = operador;
            this.valorUmbral = valorUmbral;
            this.metrica = metrica;
            this.unidad = unidad;
        }

        /**
         * Evaluates whether the given metric value triggers this rule.
         *
         * @param valorActual current value of the bound metric
         * @return {@code true} when the rule condition is met
         */
        public abstract boolean evaluar(double valorActual);

        /**
         * Returns the numeric contract code sent to the MIPS stage when
         * this rule fires.
         *
         * @return the MIPS contract code (10, 20, 30 or 40)
         */
        public abstract int getCodigoMips();

        /**
         * @return the rule identifier as declared in the DSL file
         */
        public String getNombreRegla() {
            return nombreRegla;
        }

        /**
         * @return the comparison operator used by this rule
         */
        public String getOperador() {
            return operador;
        }

        /**
         * @return the threshold value this rule compares against
         */
        public double getValorUmbral() {
            return valorUmbral;
        }

        /**
         * @return the name of the Fortran metric this rule reads
         */
        public String getMetrica() {
            return metrica;
        }

        /**
         * @return the display unit for this rule's metric
         */
        public String getUnidad() {
            return unidad;
        }

        /**
         * Applies this rule's operator to compare {@code valorActual}
         * against the configured threshold.
         *
         * @param valorActual current value of the bound metric
         * @return {@code true} when the comparison holds; {@code false}
         *         for an unrecognized operator (should not happen after
         *         DSL validation in {@link #parsearReglas(Path)})
         */
        protected boolean comparar(double valorActual) {

            return switch (operador) {
                case ">" -> valorActual > valorUmbral;
                case "<" -> valorActual < valorUmbral;
                case ">=" -> valorActual >= valorUmbral;
                case "<=" -> valorActual <= valorUmbral;
                default -> false;
            };
        }
    }

    /**
     * High-temperature rule. Bound to {@code AVERAGE_TEMPERATURE}.
     */
    public static final class ReglaTemperatura extends Regla {

        /**
         * @param nombreRegla rule identifier
         * @param operador comparison operator
         * @param valorUmbral threshold value
         */
        public ReglaTemperatura(
                String nombreRegla,
                String operador,
                double valorUmbral) {

            super(
                    nombreRegla,
                    operador,
                    valorUmbral,
                    "AVERAGE_TEMPERATURE",
                    "C");
        }

        /** {@inheritDoc} */
        @Override
        public boolean evaluar(double valorActual) {
            return comparar(valorActual);
        }

        /** {@inheritDoc} */
        @Override
        public int getCodigoMips() {
            return 10;
        }
    }

    /**
     * Heavy-rain rule. Bound to {@code TOTAL_PRECIPITATION}.
     */
    public static final class ReglaPrecipitacion extends Regla {

        /**
         * @param nombreRegla rule identifier
         * @param operador comparison operator
         * @param valorUmbral threshold value
         */
        public ReglaPrecipitacion(
                String nombreRegla,
                String operador,
                double valorUmbral) {

            super(
                    nombreRegla,
                    operador,
                    valorUmbral,
                    "TOTAL_PRECIPITATION",
                    "mm");
        }

        /** {@inheritDoc} */
        @Override
        public boolean evaluar(double valorActual) {
            return comparar(valorActual);
        }

        /** {@inheritDoc} */
        @Override
        public int getCodigoMips() {
            return 20;
        }
    }

    /**
     * Strong-wind rule. Bound to {@code MAX_WIND}.
     *
     * <p>{@code MAX_WIND} is used, rather than the average, because the
     * rule represents a peak gust condition.</p>
     */
    public static final class ReglaViento extends Regla {

        /**
         * @param nombreRegla rule identifier
         * @param operador comparison operator
         * @param valorUmbral threshold value
         */
        public ReglaViento(
                String nombreRegla,
                String operador,
                double valorUmbral) {

            super(
                    nombreRegla,
                    operador,
                    valorUmbral,
                    "MAX_WIND",
                    "km/h");
        }

        /** {@inheritDoc} */
        @Override
        public boolean evaluar(double valorActual) {
            return comparar(valorActual);
        }

        /** {@inheritDoc} */
        @Override
        public int getCodigoMips() {
            return 30;
        }
    }

    /**
     * Low-battery rule. Bound to {@code AVERAGE_BATTERY}.
     */
    public static final class ReglaBateria extends Regla {

        /**
         * @param nombreRegla rule identifier
         * @param operador comparison operator
         * @param valorUmbral threshold value
         */
        public ReglaBateria(
                String nombreRegla,
                String operador,
                double valorUmbral) {

            super(
                    nombreRegla,
                    operador,
                    valorUmbral,
                    "AVERAGE_BATTERY",
                    "%");
        }

        /** {@inheritDoc} */
        @Override
        public boolean evaluar(double valorActual) {
            return comparar(valorActual);
        }

        /** {@inheritDoc} */
        @Override
        public int getCodigoMips() {
            return 40;
        }
    }
  
    /**
     * Parses the external DSL rule file.
     *
     * <p>
     * Grammar:</p>
     * <pre>
     * &lt;regla&gt; ::= &lt;identificador&gt; &lt;operador&gt; &lt;numero&gt;
     * &lt;operador&gt; ::= "&gt;" | "&lt;" | "&gt;=" | "&lt;="
     * &lt;identificador&gt; ::= "TEMP_ALTA" | "LLUVIA_INTENSA"
     *                  | "VIENTO_FUERTE" | "BATERIA_BAJA"
     * </pre>
     *
     * <p>
     * Blank lines and lines starting with {@code #} are treated as comments and
     * skipped. An individual malformed rule is ignored so that one invalid line
     * does not stop the complete file from being parsed. If no valid rules
     * remain after parsing, the Stage 3 process reports an error instead of
     * treating the system as {@code SYSTEM_OK}. If the same rule identifier
     * appears more than once, the last valid occurrence wins and a warning is
     * printed to standard error.</p>
     *
     * @param path path to the DSL rules file (e.g. {@code data/reglas.txt})
     * @return an ordered map from rule identifier to the parsed {@link Regla}
     * instance
     * @throws IOException if the file does not exist, cannot be read, or
     * contains no valid rules
     */
    public static Map<String, Regla> parsearReglas(Path path)
            throws IOException {

        Map<String, Regla> reglas = new LinkedHashMap<>();

        if (!Files.isRegularFile(path)) {
            throw new IOException(
                    "Rules file not found: " + path);
        }

        List<String> lines = Files.readAllLines(
                path,
                StandardCharsets.UTF_8);

        for (String line : lines) {

            String trimmed = line.trim();

            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue;
            }

            String[] tokens = trimmed.split("\\s+");

            if (tokens.length != 3) {
                continue;
            }

            String identifier = tokens[0];
            String operator = tokens[1];
            String number = tokens[2];

            if (!isValidIdentifier(identifier)
                    || !isValidOperator(operator)
                    || !isValidNumber(number)) {
                continue;
            }

            double threshold;

            try {
                threshold = Double.parseDouble(number);
            } catch (NumberFormatException exception) {
                continue;
            }

            Regla rule = createRule(
                    identifier,
                    operator,
                    threshold);

            if (rule != null) {

                if (reglas.containsKey(identifier)) {

                    System.err.println(
                            "[WARNING] Duplicate rule identifier '"
                            + identifier
                            + "' in "
                            + path
                            + ". The last definition will be used.");
                }

                reglas.put(identifier, rule);
            }
        }

        return reglas;
    }

    /**
     * Reads the Fortran metric CSV produced by Stage 2.
     *
     * <p>
     * The file's first line is treated as a header and skipped. Each remaining
     * line is expected to be {@code METRIC,VALUE}. Blank or malformed metric
     * lines are ignored during parsing. During rule evaluation, however, any
     * metric required by a valid rule but absent from this file causes Stage 3
     * to fail, because the inter-stage contract has not been satisfied.</p>
     *
     * @param path path to the metrics file (e.g. {@code data/metricas.csv})
     * @return a map from metric name to its numeric value
     * @throws IOException if the file does not exist or cannot be read
     */
    private static Map<String, Double> readMetrics(
            Path path) throws IOException {

        Map<String, Double> metrics = new LinkedHashMap<>();

        if (!Files.isRegularFile(path)) {
            throw new IOException(
                    "Metrics file not found: " + path);
        }

        List<String> lines = Files.readAllLines(
                path,
                StandardCharsets.UTF_8);

        for (int i = 1; i < lines.size(); i++) {

            String line = lines.get(i).trim();

            if (line.isEmpty()) {
                continue;
            }

            String[] parts = line.split(",", 2);

            if (parts.length != 2) {
                continue;
            }

            try {
                metrics.put(
                        parts[0].trim(),
                        Double.parseDouble(parts[1].trim()));
            } catch (NumberFormatException exception) {
                // Ignore malformed metric; the rest of the file is
                // still usable.
            }
        }

        return metrics;
    }

    /**
     * Executes Stage 3 end to end: reads the Fortran metrics, parses the
     * DSL rules, evaluates every rule against its metric, and writes the
     * alert CSV, the MIPS numeric sequence and the HTML dashboard.
     *
     * <p>When no rule fires, a single {@code SYSTEM_OK} alert row and a
     * MIPS sequence containing only {@code 0} are written, matching the
     * official DSL-to-MIPS contract.</p>
     *
     * @param projectRoot root directory of the PolyFlow project,
     *         expected to contain a {@code data} subdirectory with
     *         {@code metricas.csv} and {@code reglas.txt}
     * @throws IOException if the metrics file, the rules file, or any
     *         output file cannot be read or written
     */
    public static void evaluateAndGenerateHtml(
            Path projectRoot) throws IOException {

        Path data = projectRoot.resolve("data");

        Path metricsPath = data.resolve("metricas.csv");
        Path rulesPath = data.resolve("reglas.txt");
        Path alertsPath = data.resolve("alertas.csv");
        Path sequencePath = data.resolve("secuencia.txt");
        Path reportPath = data.resolve("reporte.html");

        Map<String, Double> metrics =
                readMetrics(metricsPath);

        Map<String, Regla> rules
                = parsearReglas(rulesPath);

        if (rules.isEmpty()) {
            throw new IOException(
                    "Rules file contains no valid rules: "
                    + rulesPath);
        }

        List<String> alerts
                = new ArrayList<>();

        List<String> sequence
                =
                new ArrayList<>();

        StringBuilder htmlAlerts =
                new StringBuilder();

        alerts.add(
                "RULE_ID,METRIC,VALUE,OPERATOR,THRESHOLD,UNIT");

        for (Regla rule : rules.values()) {

            Double currentValue
                    = metrics.get(rule.getMetrica());

            if (currentValue == null) {
                throw new IOException(
                        "Required metric not found: "
                        + rule.getMetrica());
            }

            if (rule.evaluar(currentValue)) {

                alerts.add(
                        rule.getNombreRegla()
                        + ","
                        + rule.getMetrica()
                        + ","
                        + currentValue
                        + ","
                        + rule.getOperador()
                        + ","
                        + rule.getValorUmbral()
                        + ","
                        + rule.getUnidad());

                sequence.add(
                        Integer.toString(
                                rule.getCodigoMips()));

                htmlAlerts
                        .append("<div class=\"alert\">")
                        .append("<strong>")
                        .append(escapeHtml(
                                rule.getNombreRegla()))
                        .append("</strong>")
                        .append("<span>")
                        .append(format(currentValue))
                        .append(" ")
                        .append(escapeHtml(
                                rule.getUnidad()))
                        .append("</span>")
                        .append("<small>")
                        .append(escapeHtml(
                                rule.getOperador()))
                        .append(" ")
                        .append(format(
                                rule.getValorUmbral()))
                        .append("</small>")
                        .append("</div>");
            }
        }

        boolean systemOk = sequence.isEmpty();

        if (systemOk) {

            sequence.add("0");

            alerts.add(
                    "SYSTEM_OK,SYSTEM,0,N/A,0,N/A");

            htmlAlerts
                    .append("<div class=\"ok\">")
                    .append("✓ All parameters are within ")
                    .append("operational limits.")
                    .append("</div>");
        }

        Files.write(
                alertsPath,
                alerts,
                StandardCharsets.UTF_8);

        Files.write(
                sequencePath,
                sequence,
                StandardCharsets.UTF_8);

        String html =
                buildHtmlReport(
                        metrics,
                        htmlAlerts.toString(),
                        systemOk);

        Files.writeString(
                reportPath,
                html,
                StandardCharsets.UTF_8);

        System.out.println(
                "Java: Rule evaluation completed successfully.");
    }

    /**
     * Builds the simple weather-style HTML dashboard shown after the
     * pipeline finishes.
     *
     * <p>Missing metrics default to {@code 0.0} via
     * {@link Map#getOrDefault} so a partially populated metrics file
     * still renders a valid report instead of throwing.</p>
     *
     * @param metrics metrics read from Stage 2's output
     * @param alerts pre-rendered HTML fragment listing the fired alerts
     *         (or the "all clear" message)
     * @param systemOk {@code true} when no rule fired
     * @return the complete HTML document as a string
     */
    private static String buildHtmlReport(
            Map<String, Double> metrics,
            String alerts,
            boolean systemOk) {

        double averageTemperature =
                metrics.getOrDefault(
                        "AVERAGE_TEMPERATURE", 0.0);

        double maxTemperature =
                metrics.getOrDefault(
                        "MAX_TEMPERATURE", 0.0);

        double minTemperature =
                metrics.getOrDefault(
                        "MIN_TEMPERATURE", 0.0);

        double totalPrecipitation =
                metrics.getOrDefault(
                        "TOTAL_PRECIPITATION", 0.0);

        double averageWind =
                metrics.getOrDefault(
                        "AVERAGE_WIND", 0.0);

        double maxWind =
                metrics.getOrDefault(
                        "MAX_WIND", 0.0);

        double averageBattery =
                metrics.getOrDefault(
                        "AVERAGE_BATTERY", 0.0);

        double recordCount =
                metrics.getOrDefault(
                        "TOTAL_RECORDS", 0.0);

        String status =
                systemOk
                        ? "NORMAL CONDITIONS"
                        : "ACTIVE ALERTS";

        return """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport"
                          content="width=device-width, initial-scale=1.0">

                    <title>PolyFlow Weather Report</title>

                    <style>
                        * {
                            box-sizing: border-box;
                        }

                        body {
                            margin: 0;
                            font-family: Arial, sans-serif;
                            background: #eef3f7;
                            color: #263238;
                        }

                        .header {
                            background: #ffffff;
                            padding: 28px;
                            border-bottom: 1px solid #d9e1e7;
                        }

                        .header h1 {
                            margin: 0;
                            font-size: 28px;
                        }

                        .header p {
                            margin: 8px 0 0;
                            color: #71808c;
                        }

                        .container {
                            max-width: 1000px;
                            margin: 30px auto;
                            padding: 0 20px;
                        }

                        .weather {
                            background: #ffffff;
                            border-radius: 14px;
                            padding: 28px;
                            margin-bottom: 20px;
                            border: 1px solid #dce4e9;
                        }

                        .weather-title {
                            color: #71808c;
                            font-size: 14px;
                            margin-bottom: 10px;
                        }

                        .temperature {
                            font-size: 52px;
                            font-weight: bold;
                        }

                        .range {
                            color: #65747e;
                            margin-top: 8px;
                        }

                        .cards {
                            display: grid;
                            grid-template-columns:
                                repeat(auto-fit, minmax(190px, 1fr));
                            gap: 14px;
                            margin-bottom: 20px;
                        }

                        .card {
                            background: #ffffff;
                            border: 1px solid #dce4e9;
                            border-radius: 12px;
                            padding: 20px;
                        }

                        .card-title {
                            font-size: 13px;
                            color: #71808c;
                            margin-bottom: 12px;
                        }

                        .card-value {
                            font-size: 25px;
                            font-weight: bold;
                        }

                        .card-extra {
                            margin-top: 7px;
                            font-size: 12px;
                            color: #71808c;
                        }

                        .panel {
                            background: #ffffff;
                            border: 1px solid #dce4e9;
                            border-radius: 12px;
                            padding: 22px;
                            margin-bottom: 20px;
                        }

                        .panel h2 {
                            margin-top: 0;
                            font-size: 20px;
                        }

                        .alert {
                            display: flex;
                            align-items: center;
                            gap: 20px;
                            padding: 15px;
                            margin-top: 10px;
                            border-left: 4px solid #d64545;
                            background: #fff5f5;
                            border-radius: 6px;
                        }

                        .alert strong {
                            min-width: 150px;
                        }

                        .alert span {
                            font-size: 18px;
                            font-weight: bold;
                        }

                        .alert small {
                            color: #71808c;
                        }

                        .ok {
                            padding: 16px;
                            background: #f1f8f3;
                            border-left: 4px solid #4b9b68;
                            border-radius: 6px;
                        }

                        .status {
                            display: inline-block;
                            margin-top: 14px;
                            padding: 7px 12px;
                            border-radius: 20px;
                            font-size: 12px;
                            font-weight: bold;
                            background: %s;
                            color: white;
                        }

                        footer {
                            text-align: center;
                            color: #71808c;
                            font-size: 12px;
                            padding: 20px;
                        }
                    </style>
                </head>

                <body>

                    <div class="header">
                        <div class="container">
                            <h1>PolyFlow Weather Report</h1>
                            <p>
                                Environmental telemetry analysis
                            </p>

                            <div class="status">
                                %s
                            </div>
                        </div>
                    </div>

                    <div class="container">

                        <div class="weather">
                            <div class="weather-title">
                                Average temperature
                            </div>

                            <div class="temperature">
                                %s °C
                            </div>

                            <div class="range">
                                Minimum: %s °C
                                &nbsp;&nbsp;|&nbsp;&nbsp;
                                Maximum: %s °C
                            </div>
                        </div>

                        <div class="cards">

                            <div class="card">
                                <div class="card-title">
                                    PRECIPITATION
                                </div>
                                <div class="card-value">
                                    %s mm
                                </div>
                                <div class="card-extra">
                                    Total recorded
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-title">
                                    WIND
                                </div>
                                <div class="card-value">
                                    %s km/h
                                </div>
                                <div class="card-extra">
                                    Average: %s km/h
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-title">
                                    BATTERY
                                </div>
                                <div class="card-value">
                                    %s %%
                                </div>
                                <div class="card-extra">
                                    Average sensor level
                                </div>
                            </div>

                            <div class="card">
                                <div class="card-title">
                                    RECORDS
                                </div>
                                <div class="card-value">
                                    %s
                                </div>
                                <div class="card-extra">
                                    Valid telemetry records
                                </div>
                            </div>

                        </div>

                        <div class="panel">

                            <h2>Weather alerts</h2>

                            %s

                        </div>

                    </div>

                    <footer>
                        PolyFlow · Polyglot Data Pipeline
                    </footer>

                </body>
                </html>
                """.formatted(
                systemOk ? "#4b9b68" : "#d64545",
                status,
                format(averageTemperature),
                format(minTemperature),
                format(maxTemperature),
                format(totalPrecipitation),
                format(maxWind),
                format(averageWind),
                format(averageBattery),
                format(recordCount),
                alerts);
    }

    /**
     * Formats a numeric value with exactly two decimal places, using a
     * fixed {@link java.util.Locale#US} locale so the output always uses
     * a dot as the decimal separator regardless of the host's default
     * locale (avoids a comma-decimal locale silently corrupting the
     * generated CSV/HTML).
     *
     * @param value value to format
     * @return the value formatted as {@code "0.00"}
     */
    private static String format(double value) {
        return String.format(
                java.util.Locale.US,
                "%.2f",
                value);
    }

    /**
     * Checks whether an identifier token is one of the four DSL
     * identifiers defined by the grammar.
     *
     * @param identifier token to validate
     * @return {@code true} when the identifier is recognized
     */
    private static boolean isValidIdentifier(
            String identifier) {

        return switch (identifier) {
            case "TEMP_ALTA",
                 "LLUVIA_INTENSA",
                 "VIENTO_FUERTE",
                 "BATERIA_BAJA" -> true;

            default -> false;
        };
    }

    /**
     * Checks whether an operator token is one of the four comparison
     * operators defined by the grammar.
     *
     * @param operator token to validate
     * @return {@code true} when the operator is recognized
     */
    private static boolean isValidOperator(
            String operator) {

        return switch (operator) {
            case ">", "<", ">=", "<=" -> true;
            default -> false;
        };
    }

    /**
     * Checks whether a threshold token is a valid signed integer or
     * decimal number, as required by the {@code <numero>} production of
     * the DSL grammar.
     *
     * @param value token to validate
     * @return {@code true} when the token can be safely parsed with
     *         {@link Double#parseDouble(String)}
     */
    private static boolean isValidNumber(
            String value) {

        return value.matches(
                "-?\\d+(\\.\\d+)?");
    }

    /**
     * Instantiates the concrete {@link Regla} subclass that corresponds
     * to a validated DSL identifier.
     *
     * @param identifier validated rule identifier
     * @param operator validated comparison operator
     * @param threshold parsed threshold value
     * @return the concrete rule instance, or {@code null} if the
     *         identifier does not map to any known rule type (should
     *         not happen once {@link #isValidIdentifier(String)} has
     *         already accepted it)
     */
    private static Regla createRule(
            String identifier,
            String operator,
            double threshold) {

        return switch (identifier) {

            case "TEMP_ALTA" ->
                new ReglaTemperatura(
                        identifier,
                        operator,
                        threshold);

            case "LLUVIA_INTENSA" ->
                new ReglaPrecipitacion(
                        identifier,
                        operator,
                        threshold);

            case "VIENTO_FUERTE" ->
                new ReglaViento(
                        identifier,
                        operator,
                        threshold);

            case "BATERIA_BAJA" ->
                new ReglaBateria(
                        identifier,
                        operator,
                        threshold);

            default -> null;
        };
    }

    /**
     * Escapes the five reserved HTML characters so metric names, units
     * and operators pulled from the DSL/metrics files cannot break or
     * inject markup into the generated report.
     *
     * @param value raw text to escape
     * @return HTML-safe text
     */
    private static String escapeHtml(String value) {

        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}