# ==============================================================================
# Module: MIPS Assembly Integrity Checksum Verifier (Stage 4)
# Language: MIPS32 Assembly
# Authors: Randall AC, Keilor MC
# Description:
#   Simulates the processing of numeric sequence codes generated by Java.
#   Applies an iterative checksum algorithm combining addition and bitwise XOR
#   operations against positional indices to verify system contract integrity.
#
# Register Mapping:
#   $t0 : Accumulator holding the running checksum result
#   $t1 : Register loading the value for position 1 (e.g., TEMP_ALTA = 10)
#   $t2 : Register loading the value for position 2 (e.g., LLUVIA_INTENSA = 20)
# ==============================================================================

.data
    # Simulated input codes read from data/secuencia.txt
    pos1: .word 10        # Code 10 = TEMP_ALTA
    pos2: .word 20        # Code 20 = LLUVIA_INTENSA
    
    # System console output strings
    success_msg: .asciiz "MIPS: Integrity Checksum Calculated: "
    newline:     .asciiz "\n"

.text
.globl main

main:
    # Initialize checksum accumulator ($t0 = 0)
    li $t0, 0
    
    # --------------------------------------------------------------------------
    # Process Item at Position 1 (Value = 10, Position Index = 1)
    # --------------------------------------------------------------------------
    lw  $t1, pos1         # Load code value for position 1 into $t1
    add $t0, $t0, $t1     # checksum = checksum + valor
    xor $t0, $t0, 1       # checksum = checksum XOR 1 (bitwise XOR with position)
    
    # --------------------------------------------------------------------------
    # Process Item at Position 2 (Value = 20, Position Index = 2)
    # --------------------------------------------------------------------------
    lw  $t2, pos2         # Load code value for position 2 into $t2
    add $t0, $t0, $t2     # checksum = checksum + valor
    xor $t0, $t0, 2       # checksum = checksum XOR 2 (bitwise XOR with position)

    # --------------------------------------------------------------------------
    # Output Results via System Calls
    # --------------------------------------------------------------------------
    # Print label message (syscall 4)
    li $v0, 4
    la $a0, success_msg
    syscall

    # Print computed checksum integer (syscall 1)
    li $v0, 1
    move $a0, $t0
    syscall

    # Print newline character (syscall 4)
    li $v0, 4
    la $a0, newline
    syscall

    # Terminate program execution safely (syscall 10)
    li $v0, 10
    syscall