# ==============================================================================
# Module: MIPS Assembly Integrity Checksum Verifier
# Stage: 4
# Language: MIPS32 Assembly
# Authors: Randall AC, Keilor MC
#
# Description:
#   Reads the numeric sequence generated by Stage 3 (Java), validates the
#   official DSL-to-MIPS numeric contract, and calculates the final checksum.
#
# Input:
#   data/secuencia.txt
#
# Official contract:
#   0  = SYSTEM OK
#   10 = TEMP_ALTA
#   20 = LLUVIA_INTENSA
#   30 = VIENTO_FUERTE
#   40 = BATERIA_BAJA
#
# Checksum algorithm:
#   checksum = checksum + valor
#   checksum = checksum XOR posicion
# ==============================================================================

.data

filepath:
    .asciiz "data/secuencia.txt"

buffer:
    .space 256

success_msg:
    .asciiz "MIPS: Integrity checksum calculated: "

err_file_msg:
    .asciiz "MIPS ERROR: Unable to open data/secuencia.txt\n"

err_code_msg:
    .asciiz "MIPS WARNING: Unrecognized contract code skipped: "

newline:
    .asciiz "\n"

.text

.globl main

main:

    # --------------------------------------------------------------------------
    # 1. Open the sequence file.
    #
    # Syscall 13:
    #   a0 = filename
    #   a1 = flags
    #   a2 = mode
    # --------------------------------------------------------------------------

    li $v0, 13

    la $a0, filepath

    li $a1, 0

    li $a2, 0

    syscall

    move $s0, $v0

    # Abort if file could not be opened.
    bltz $s0, handle_file_error


    # --------------------------------------------------------------------------
    # 2. Read the sequence file.
    #
    # Syscall 14:
    #   a0 = file descriptor
    #   a1 = buffer
    #   a2 = maximum bytes
    # --------------------------------------------------------------------------

    li $v0, 14

    move $a0, $s0

    la $a1, buffer

    li $a2, 256

    syscall

    move $s1, $v0


    # --------------------------------------------------------------------------
    # 3. Close the file.
    # --------------------------------------------------------------------------

    li $v0, 16

    move $a0, $s0

    syscall


    # --------------------------------------------------------------------------
    # Stop safely if no bytes were read.
    # --------------------------------------------------------------------------

    blez $s1, print_results


    # --------------------------------------------------------------------------
    # 4. Initialize processing registers.
    #
    # t0 = checksum
    # t6 = position
    # t7 = current integer
    # t8 = buffer index
    # t9 = number-in-progress flag
    # --------------------------------------------------------------------------

    li $t0, 0

    li $t6, 1

    li $t7, 0

    li $t8, 0

    li $t9, 0


parse_loop:

    # End of buffer.
    bge $t8, $s1, finalize_last_number


    # Calculate address of current byte.
    la $t2, buffer

    add $t2, $t2, $t8

    lb $t3, 0($t2)


    # --------------------------------------------------------------------------
    # Check whether current byte is an ASCII digit.
    #
    # '0' = 48
    # '9' = 57
    # --------------------------------------------------------------------------

    blt $t3, 48, check_separator

    bgt $t3, 57, check_separator


    # Convert ASCII digit to integer.
    sub $t3, $t3, 48

    mul $t7, $t7, 10

    add $t7, $t7, $t3

    li $t9, 1

    j next_char


check_separator:

    # No number currently being parsed.
    beq $t9, $zero, next_char


    # Process the completed number.
    jal process_and_accumulate


    # Reset number parser.
    li $t7, 0

    li $t9, 0


next_char:

    addi $t8, $t8, 1

    j parse_loop


finalize_last_number:

    # Process final number when the file does not end with a separator.
    beq $t9, $zero, print_results

    jal process_and_accumulate


print_results:

    # --------------------------------------------------------------------------
    # Print checksum label.
    # --------------------------------------------------------------------------

    li $v0, 4

    la $a0, success_msg

    syscall


    # --------------------------------------------------------------------------
    # Print checksum integer.
    # --------------------------------------------------------------------------

    li $v0, 1

    move $a0, $t0

    syscall


    # --------------------------------------------------------------------------
    # Print newline.
    # --------------------------------------------------------------------------

    li $v0, 4

    la $a0, newline

    syscall

    j end_program


# ==============================================================================
# Subroutine: process_and_accumulate
#
# Validates the MIPS contract code and applies:
#
#   checksum = checksum + value
#   checksum = checksum XOR position
#
# Position is incremented only for valid contract values.
# Invalid values are ignored.
# ==============================================================================

process_and_accumulate:

    # --------------------------------------------------------------------------
    # Official contract validation.
    # --------------------------------------------------------------------------

    beq $t7, $zero, valid_code

    li $t4, 10
    beq $t7, $t4, valid_code

    li $t4, 20
    beq $t7, $t4, valid_code

    li $t4, 30
    beq $t7, $t4, valid_code

    li $t4, 40
    beq $t7, $t4, valid_code


    # --------------------------------------------------------------------------
    # Invalid code: warn and ignore.
    # --------------------------------------------------------------------------

    li $v0, 4

    la $a0, err_code_msg

    syscall

    li $v0, 1

    move $a0, $t7

    syscall

    li $v0, 4

    la $a0, newline

    syscall

    jr $ra


valid_code:

    # --------------------------------------------------------------------------
    # Checksum step 1:
    #
    # checksum = checksum + value
    # --------------------------------------------------------------------------

    add $t0, $t0, $t7


    # --------------------------------------------------------------------------
    # Checksum step 2:
    #
    # checksum = checksum XOR position
    # --------------------------------------------------------------------------

    xor $t0, $t0, $t6


    # Move to next valid sequence position.
    addi $t6, $t6, 1

    jr $ra


handle_file_error:

    li $v0, 4

    la $a0, err_file_msg

    syscall

    # Exit with a non-zero status so the Java orchestrator
    # detects the Stage 4 failure.
    li $v0, 17
    li $a0, 1
    syscall

end_program:

    li $v0, 10

    syscall
